# Generated by Django 5.0.2 on 2024-04-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='loginID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
