# Generated by Django 5.0.2 on 2024-04-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_email_employee_loginid_remove_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginID', models.CharField(max_length=100)),
            ],
        ),
    ]
