# Generated by Django 5.0.2 on 2024-04-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='loginID',
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
