# Generated by Django 5.0.2 on 2024-04-16 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_employee_email_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportType', models.CharField(choices=[('Coding Error', 'Coding Error'), ('Design Issue', 'Design Issue'), ('Suggestion', 'Suggestion'), ('Documentation', 'Documentation'), ('Hardware', 'Hardware'), ('Query', 'Query')], max_length=100)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Serious', 'Serious'), ('Fatal', 'Fatal')], max_length=100)),
                ('attachment', models.CharField(max_length=100)),
                ('problemSummary', models.TextField()),
                ('isReproducible', models.BooleanField()),
                ('problem', models.TextField()),
                ('suggestedFix', models.TextField()),
                ('reportedOn', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=100)),
                ('priority', models.CharField(choices=[('Fix immediately', 'Fix immediately'), ('Fix as soon as possible', 'Fix as soon as possible'), ('Fix before next milestone', 'Fix before next milestone'), ('Fix before release', 'Fix before release'), ('Fix if possible', 'Fix if possible'), ('Optional', 'Optional')], default='Optional', max_length=100)),
                ('resolution', models.CharField(choices=[('Pending', 'Pending'), ('Fixed', 'Fixed'), ('Cannot be reproduced', 'Cannot be reproduced'), ('Deferred', 'Deferred'), ('As designed', 'As designed'), ('Withdrawn by reporter', 'Withdrawn by reporter'), ('Need more info', 'Need more info'), ('Disagree with suggestion', 'Disagree with suggestion'), ('Duplicate', 'Duplicate')], default='Pending', max_length=100)),
                ('resolvedOn', models.DateTimeField(blank=True, null=True)),
                ('testedOn', models.DateTimeField(blank=True, null=True)),
                ('isDeferred', models.BooleanField(default=False)),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='webapp.employee')),
                ('functionalArea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.functionalarea')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.program')),
                ('reportedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='webapp.employee')),
                ('resolvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved', to='webapp.employee')),
                ('testedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tested', to='webapp.employee')),
            ],
        ),
    ]
