# Generated by Django 5.0.2 on 2024-04-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_login_loginid_login_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='reportType',
            field=models.CharField(choices=[('Select', 'Select'), ('Coding Error', 'Coding Error'), ('Design Issue', 'Design Issue'), ('Suggestion', 'Suggestion'), ('Documentation', 'Documentation'), ('Hardware', 'Hardware'), ('Query', 'Query')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='severity',
            field=models.CharField(choices=[('Select', 'Select'), ('Minor', 'Minor'), ('Serious', 'Serious'), ('Fatal', 'Fatal')], max_length=100),
        ),
    ]
