# Generated by Django 5.0.2 on 2024-04-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_bugreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='level',
        ),
    ]
