# Generated by Django 5.0.2 on 2024-04-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_bugreport_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
