# Generated by Django 5.0.2 on 2024-04-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_role_employee_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionalarea',
            name='description',
        ),
        migrations.AddField(
            model_name='functionalarea',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.program'),
        ),
    ]
